import { test, expect } from '@playwright/test';

test('register, ingest, inspect a trace, change privacy and revoke a key',async({page,request},testInfo)=>{
 const suffix=crypto.randomUUID().replaceAll('-','');
 await page.goto('/');
 await page.getByLabel('Organization',{exact:true}).fill('Rubberai browser test');
 await page.getByLabel('Your name').fill('Test Developer');
 await page.getByLabel('Username',{exact:true}).fill('browser_'+suffix);
 await page.getByLabel('Password',{exact:true}).fill('Browser-test-password-123');
 await page.getByRole('button',{name:'Create workspace'}).click();
 await expect(page.getByRole('heading',{name:'AI activity, understood.'})).toBeVisible();
 await page.getByLabel('Project name',{exact:true}).fill('Cross-language service');
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await expect(page.getByText('No user prompts recorded in this period.')).toBeVisible();
 await page.getByRole('button',{name:'Connect a project',exact:true}).click();
 await page.getByRole('button',{name:'Generate key'}).click();
 const key=await page.locator('.key-reveal code').innerText();
 const project=await page.locator('#project').inputValue();
 const base={project_id:project,user_id:'external-python-developer',session_id:'session_'+suffix,trace_id:'trace_'+suffix,prompt_id:'prompt_'+suffix,timestamp:new Date().toISOString(),agent:{name:'custom-agent'},ide:{name:'any-ide'},language:'python'};
 const events=[{...base,event_id:'prompt_'+suffix,event_type:'prompt.created',prompt:'sensitive prompt must not be stored'}, {...base,event_id:'llm_'+suffix,event_type:'llm.request.completed',model:{provider:'custom',name:'model'},usage:{input_tokens:1000,output_tokens:500,cached_tokens:200,reasoning_tokens:100},cost:{amount:'0.012',currency:'USD',type:'actual'}},{...base,event_id:'file_'+suffix,event_type:'file.modified',file:{path:'src/retry.py',lines_added:12,lines_removed:3,change_source:'AI',evidence:'agent edit tool-1'}},{...base,event_id:'tool_'+suffix,event_type:'tool.completed',tool_name:'run_tests',status:'passed'}];
 events.push(...['second','third'].map(id=>({...base,event_id:id+suffix,event_type:'prompt.created',prompt_id:id+suffix,trace_id:id+suffix,prompt:'another human prompt'})));
 events.push({...base,event_id:'orphan'+suffix,event_type:'llm.request.completed',prompt_id:'unassigned',model:{provider:'custom',name:'model'},usage:{input_tokens:9000,output_tokens:1}});
 const response=await request.post('/api/v1/events',{headers:{Authorization:'Bearer '+key},data:{events}});
 expect(response.status()).toBe(200);expect((await response.json()).accepted).toBe(7);
 await page.getByRole('button',{name:'Dismiss key'}).click();
 await page.getByRole('button',{name:'Activity overview',exact:true}).click();
 await page.getByRole('button',{name:'Apply filters',exact:true}).click();
 await expect(page.locator('.stats')).toContainText('1,500');
 await expect(page.locator('.turn')).toHaveCount(3);
 await page.screenshot({path:testInfo.outputPath('prompts.png'),fullPage:true});
 await page.locator('tbody tr').filter({hasText:'1,000'}).locator('.turn').click();
 await page.screenshot({path:testInfo.outputPath('prompt-detail.png'),fullPage:true});
 await expect(page.locator('.prompt-detail')).toContainText('1,000');
 await expect(page.locator('.prompt-detail')).toContainText('500');
 await expect(page.locator('.prompt-detail')).toContainText('200');
 await expect(page.locator('.prompt-detail')).toContainText('Not reported');
 await page.locator('.internal-activity > summary').click();
 await page.getByRole('button',{name:'View trace'}).first().click();
 await expect(page.getByRole('heading',{name:'Trace timeline'})).toBeVisible();
 await expect(page.getByRole('button',{name:'Apply filters',exact:true})).toBeEnabled();
 await page.getByRole('button',{name:'prompt.created',exact:true}).click();
 await expect(page.locator('.detail')).not.toContainText('sensitive prompt');
 await expect(page.locator('.detail')).toContainText('prompt_'+suffix);
 await page.screenshot({path:testInfo.outputPath('trace.png'),fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);
 expect(overflow).toBe(false);
 await page.getByRole('button',{name:'Privacy & settings',exact:true}).click();
 await page.getByLabel('Privacy mode').selectOption('FULL');
 await page.getByLabel('Allow diffs in full collection mode').check();
 await page.getByRole('button',{name:'Save settings'}).click();
 await expect(page.locator('header .badge')).toContainText('Full collection');
 await page.getByRole('button',{name:'Connect a project',exact:true}).click();
 await page.getByRole('button',{name:'Revoke',exact:true}).click();
 await expect(page.getByRole('cell',{name:'Revoked',exact:true})).toBeVisible();
 expect((await request.post('/api/v1/events',{headers:{Authorization:'Bearer '+key},data:events[0]})).status()).toBe(401);
 await page.getByRole('button',{name:'Sign out',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Start with an organization'})).toBeVisible();
});
