<script lang="ts">
 import { onMount } from 'svelte';
 type Project={id:string;name:string;description:string;repository_url:string;privacy:string;track_diffs:boolean};
 type Activity={event_id:string;event_type:string;timestamp:string;user_id?:string;session_id?:string;trace_id?:string;prompt_id?:string;prompt?:string;file?:{path:string;change_source?:string};agent?:{name?:string};model?:{name?:string};[key:string]:unknown};
 type Stats={events:number;prompts:number;requests:number;total_tokens:number;sessions:number;traces:number;files_changed:number;lines_added:number;lines_removed:number;requests_with_total:number;requests_with_cost:number;tools:number;prompt_text:string|null;models:string[]|null;started_at:string|null;ended_at:string|null;[key:string]:unknown};
 type Analytics={totals:Stats;costs:{amount:string;currency:string;type:string}[];breakdown:{name:string;stats:Stats}[]};
 type Key={id:string;name:string;revoked_at:string|null};
 let me:{id:string;display_name:string;organization_id:string}|null=$state(null),ready=$state(false),register=$state(true),busy=$state(false),error=$state('');
 let username=$state(''),password=$state(''),displayName=$state(''),organization=$state('');
 let projects:Project[]=$state([]),selected=$state(''),newName=$state(''),view=$state('activity');
 let analytics:Analytics|null=$state(null),events:Activity[]=$state([]),keys:Key[]=$state([]),issuedKey=$state(''),keyName=$state('Local development');
 let group=$state('user'),userFilter=$state(''),agentFilter=$state(''),modelFilter=$state(''),traceFilter=$state(''),promptFilter=$state(''),languageFilter=$state(''),ideFilter=$state(''),sessionFilter=$state(''),repositoryFilter=$state(''),branchFilter=$state(''),eventFilter=$state('');
 let from=$state(new Date(Date.now()-30*86400000).toISOString().slice(0,10)),to=$state(new Date().toISOString().slice(0,10));
 let detail:Activity|null=$state(null),hasMore=$state(false),offset=$state(0),privacy=$state('METADATA_ONLY'),trackDiffs=$state(false);
 const project=$derived(projects.find(p=>p.id===selected));
 const number=(v:number|undefined)=>new Intl.NumberFormat().format(v??0);
 async function api(path:string,method='GET',body?:unknown){const res=await fetch('/api/v1'+path,{method,headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const value=await res.json();if(!res.ok)throw new Error(value.error?.message||'Request failed');return value;}
 async function action(fn:()=>Promise<void>){busy=true;error='';try{await fn()}catch(e){error=e instanceof Error?e.message:'Request failed'}finally{busy=false}}
 function query(){const p=new URLSearchParams({from:new Date(from+'T00:00:00Z').toISOString(),to:new Date(to+'T23:59:59.999Z').toISOString(),group_by:group});for(const [key,value]of Object.entries({user_id:userFilter,agent:agentFilter,model:modelFilter,trace_id:traceFilter,prompt_id:promptFilter,language:languageFilter,ide:ideFilter,session_id:sessionFilter,repository:repositoryFilter,branch:branchFilter,event_type:eventFilter})){if(value)p.set(key,value)}return p}
 async function refresh(){if(!selected)return;const p=query();const [a,e,k]=await Promise.all([api(`/projects/${selected}/analytics?${p}`),api(`/projects/${selected}/events?${p}`),api(`/projects/${selected}/keys`)]);analytics=a;events=e.events;hasMore=e.has_more;offset=e.next_offset;keys=k;privacy=project?.privacy??'METADATA_ONLY';trackDiffs=project?.track_diffs??false;}
 async function loadProjects(){projects=await api('/projects');if(!selected&&projects.length)selected=projects[0].id;await refresh()}
 async function authenticate(){await action(async()=>{me=await api('/auth/'+(register?'register':'login'),'POST',{username,password,display_name:displayName,organization});password='';await loadProjects()})}
 async function createProject(){await action(async()=>{const p=await api('/projects','POST',{name:newName});selected=p.id;newName='';await loadProjects()})}
 async function selectProject(){detail=null;issuedKey='';traceFilter='';promptFilter='';await action(refresh)}
 async function inspectTrace(id:string){traceFilter=id;promptFilter='';view='activity';detail=null;await action(refresh)}
 async function inspectPrompt(id:string){promptFilter=id;traceFilter='';view='activity';detail=null;await action(refresh)}
 onMount(()=>{(async()=>{try{me=await api('/me');await loadProjects()}catch(e){if(me)error=e instanceof Error?e.message:'Could not load projects'}finally{ready=true}})()});
</script>

<svelte:head><meta name="description" content="Understand AI coding activity across your projects, tools and models."/></svelte:head>
{#if !ready}<main class="loading">Loading rubberai…</main>
{:else if !me}
 <main class="welcome"><section class="pitch"><a class="brand" href="/">rubber<span>ai</span><i></i></a><div class="eyebrow">DEVELOPER OBSERVABILITY</div><h1>Every AI action.<br/>One clear picture.</h1><p>Connect prompts, tools, tokens and code changes. Understand what happened, without guessing who did it.</p><div class="principles"><span>Any agent</span><span>Any language</span><span>Privacy first</span></div></section>
 <section class="auth card"><div class="eyebrow">YOUR WORKSPACE</div><h2>{register?'Start with an organization':'Welcome back'}</h2><p class="muted">{register?'Create your account. No email address required.':'Sign in to explore your development activity.'}</p>
 <form onsubmit={e=>{e.preventDefault();authenticate()}}>
 {#if register}<label>Organization<input bind:value={organization} maxlength="120" required placeholder="Acme engineering"/></label><label>Your name<input bind:value={displayName} maxlength="120" required placeholder="Display name" autocomplete="name"/></label>{/if}
 <label>Username<input bind:value={username} required autocomplete="username" maxlength="160"/></label><label>Password<input type="password" bind:value={password} required minlength={register?12:1} maxlength="256" autocomplete={register?'new-password':'current-password'}/></label>
 {#if error}<p role="alert" class="error">{error}</p>{/if}<button class="primary" disabled={busy}>{busy?'Working…':register?'Create workspace →':'Sign in →'}</button></form>
 <button class="text-button" onclick={()=>{register=!register;error=''}}>{register?'Already have an account? Sign in':'Create an organization'}</button></section></main>
{:else}
 <div class="shell"><aside><a class="brand" href="/">rubber<span>ai</span><i></i></a><div class="eyebrow">WORKSPACE</div><label class="sr-only" for="project">Project</label><select id="project" bind:value={selected} onchange={selectProject} disabled={busy}>{#each projects as p}<option value={p.id}>{p.name}</option>{/each}</select><nav>{#each [['activity','Activity overview'],['keys','Connect a project'],['settings','Privacy & settings']] as [id,label]}<button class:active={view===id} onclick={()=>view=id}>{label}</button>{/each}</nav><div class="sidebar-bottom"><span class="avatar">{me.display_name.slice(0,1).toUpperCase()}</span><div>{me.display_name}<small>Organization workspace</small></div><button class="text-button" onclick={()=>action(async()=>{await api('/auth/logout','POST');me=null;projects=[];selected='';events=[];analytics=null;keys=[];issuedKey='';detail=null})}>Sign out</button></div></aside>
 <main class="workspace"><header><div><div class="eyebrow">OBSERVE / {view==='activity'?'OVERVIEW':view.toUpperCase()}</div><h1>{view==='activity'?'AI activity, understood.':view==='keys'?'Connect your tools.':'Your data, your rules.'}</h1><p class="muted">{project?project.name:'Create your first project to start collecting events.'}</p></div><span class="badge">{project?.privacy==='FULL'?'Full collection':project?.privacy==='REDACTED'?'Redacted collection':'Metadata first'}</span></header>
 {#if error}<div class="error" role="alert">{error}</div>{/if}
 <details class="new-project" open={!projects.length}><summary>Add a project</summary><form class="inline" onsubmit={e=>{e.preventDefault();createProject()}}><label>Project name<input bind:value={newName} required maxlength="120" placeholder="My project"/></label><button class="primary" disabled={busy}>Create project</button></form></details>
 {#if project}
 {#if view==='activity'}
 <form class="filters card" onsubmit={e=>{e.preventDefault();detail=null;action(refresh)}}><label>From (UTC)<input type="date" bind:value={from} required/></label><label>To (UTC)<input type="date" bind:value={to} required/></label><label>User<input bind:value={userFilter} placeholder="Any user ID"/></label><label>Agent<input bind:value={agentFilter} placeholder="Any agent"/></label><label>Model<input bind:value={modelFilter} placeholder="Any model"/></label><button class="primary" disabled={busy}>{busy?'Loading…':'Apply filters'}</button><details class="advanced"><summary>More filters</summary><div class="filters"><label>IDE<input bind:value={ideFilter}/></label><label>Language<input bind:value={languageFilter}/></label><label>Repository<input bind:value={repositoryFilter}/></label><label>Branch<input bind:value={branchFilter}/></label><label>Event type<input bind:value={eventFilter}/></label><label>Session ID<input bind:value={sessionFilter}/></label><label>Trace ID<input bind:value={traceFilter}/></label><label>Prompt ID<input bind:value={promptFilter}/></label></div></details></form>
 {#if traceFilter||promptFilter}<div class="focus-banner"><span>Inspecting {traceFilter?'trace':'prompt'} <code>{traceFilter||promptFilter}</code></span><button onclick={()=>{traceFilter='';promptFilter='';action(refresh)}}>Clear focus</button></div>{/if}
 {#if analytics}<section class="stats">{#each [['Prompts',analytics.totals.prompts],['Reported total tokens',analytics.totals.total_tokens],['Traces',analytics.totals.traces],['Files changed',analytics.totals.files_changed]] as [label,value]}<article class="card"><span class="muted">{label}</span><strong>{number(Number(value))}</strong></article>{/each}</section>
 <div class="two-col"><section class="card"><div class="section-title"><h2>Usage breakdown</h2><label><span class="sr-only">Group by</span><select bind:value={group} onchange={()=>action(refresh)}>{#each ['prompt','trace','user','agent','model','ide','language','day'] as g}<option value={g}>{g}</option>{/each}</select></label></div><div class="table-scroll"><table><thead><tr><th>{group==='prompt'?'your prompt':group==='trace'?'trace':group}</th><th>Requests</th><th>Tools</th><th>Tokens</th><th>Files</th></tr></thead><tbody>{#each analytics.breakdown as b}<tr><td>{#if group==='prompt'&&b.name!=='unknown'}<button class="text-button turn" title={b.stats.prompt_text||b.name} onclick={()=>inspectPrompt(b.name)}>{b.stats.prompt_text||'(prompt text not captured)'}</button>{#if b.stats.models?.length}<span class="badge">{b.stats.models.join(', ')}</span>{/if}{:else if group==='trace'&&b.name!=='unknown'}<button class="text-button turn" onclick={()=>inspectTrace(b.name)}>{b.stats.prompt_text||b.name}</button>{:else if group==='user'&&b.name!=='unknown'}<button class="text-button" onclick={()=>{userFilter=b.name;action(refresh)}}>{b.name}</button>{:else}{b.name}{/if}</td><td>{number(b.stats.requests)}</td><td>{number(b.stats.tools)}</td><td>{number(b.stats.total_tokens)}</td><td>{number(b.stats.files_changed)}</td></tr>{:else}<tr><td colspan="5" class="muted">No activity in this period.</td></tr>{/each}</tbody></table></div><p class="caption">Top 100 groups. Missing token totals remain unknown.</p></section>
 <section class="card"><h2>Recorded cost</h2>{#each analytics.costs as cost}<div class="cost"><strong>{cost.currency} {cost.amount}</strong><span class="badge">{cost.type}</span></div>{:else}<p class="muted">No costs reported. Configure model pricing or send provider charges with events.</p>{/each}<div class="coverage"><span>Usage coverage</span><strong>{analytics.totals.requests_with_total} / {analytics.totals.requests} requests include totals</strong><span>Cost coverage</span><strong>{analytics.totals.requests_with_cost} / {analytics.totals.requests} requests include costs</strong></div><p class="caption">Currencies are kept separate. Usage is not a developer performance score.</p></section></div>{/if}
 <section class="card timeline"><div class="section-title"><div><h2>{traceFilter?'Trace timeline':promptFilter?'Prompt activity':'Activity timeline'}</h2><p class="muted">Chronological events, linked by the IDs your integration provides.</p></div><span class="badge">{events.length} loaded</span></div>{#each events as event}<article class="event"><div class="dot"></div><time>{new Date(event.timestamp).toLocaleString()}</time><div class="event-main"><button class="event-title" onclick={()=>detail=event}>{event.event_type}</button><p>{event.file?.path||event.prompt||event.agent?.name||event.user_id||'Metadata event'}</p><div class="event-links">{#if event.trace_id}<button class="text-button" onclick={()=>inspectTrace(event.trace_id!)}>View trace ↗</button>{/if}{#if event.prompt_id}<button class="text-button" onclick={()=>inspectPrompt(event.prompt_id!)}>View prompt ↗</button>{/if}</div></div>{#if event.file}<span class="badge">{event.file.change_source||'UNKNOWN'}</span>{/if}</article>{:else}<div class="empty"><h3>Your next AI session starts here.</h3><p>Generate a project key and send your first event to see prompts, usage and file changes together.</p><button class="primary" onclick={()=>view='keys'}>Connect a tool →</button></div>{/each}{#if hasMore}<button disabled={busy} onclick={()=>action(async()=>{const p=query();p.set('offset',String(offset));const e=await api(`/projects/${selected}/events?${p}`);events=[...events,...e.events];hasMore=e.has_more;offset=e.next_offset})}>Load more events</button>{/if}</section>
 {#if detail}<section class="card detail"><div class="section-title"><h2>Event detail</h2><button onclick={()=>detail=null}>Close</button></div><p class="muted">Prompt text is optional. Relationships are reported by the integration.</p><pre>{JSON.stringify(detail,null,2)}</pre></section>{/if}
 {:else if view==='keys'}<section class="card"><h2>Project ingestion keys</h2><p class="muted">Keys can only send events to this project. Store them in your tool’s environment.</p><form class="inline" onsubmit={e=>{e.preventDefault();action(async()=>{const key=await api(`/projects/${selected}/keys`,'POST',{name:keyName});issuedKey=key.api_key;keys=await api(`/projects/${selected}/keys`)})}}><label>Key name<input bind:value={keyName} required maxlength="120"/></label><button class="primary" disabled={busy}>Generate key</button></form>{#if issuedKey}<div class="key-reveal"><strong>Copy this key now. It is shown only once.</strong><code>{issuedKey}</code><button onclick={()=>issuedKey=''}>Dismiss key</button></div>{/if}<div class="table-scroll"><table><thead><tr><th>Name</th><th>Status</th><th>Action</th></tr></thead><tbody>{#each keys as key}<tr><td>{key.name}</td><td>{key.revoked_at?'Revoked':'Active'}</td><td>{#if !key.revoked_at}<button disabled={busy} onclick={()=>action(async()=>{await api(`/projects/${selected}/keys/${key.id}`,'DELETE');keys=await api(`/projects/${selected}/keys`)})}>Revoke</button>{/if}</td></tr>{/each}</tbody></table></div><p class="caption">To rotate a key, generate a replacement, update your integration, then revoke the old key.</p></section><section class="card"><h2>Send your first event</h2><p>Use the project ID below with the documented HTTP API or Python SDK.</p><pre>{`POST /api/v1/events
Authorization: Bearer <YOUR_API_KEY>
Content-Type: application/json

${JSON.stringify({event_id:'evt_unique_id',event_type:'prompt.created',project_id:selected,user_id:me.id,session_id:'session_1',trace_id:'trace_1',prompt_id:'prompt_1',timestamp:new Date().toISOString()},null,2)}`}</pre><p class="caption">Keep the same event ID when retrying. The server counts it once.</p></section>
 {:else}<section class="card"><h2>Collection policy</h2><form onsubmit={e=>{e.preventDefault();action(async()=>{await api(`/projects/${selected}`,'PATCH',{privacy,track_diffs:trackDiffs});await loadProjects()})}}><label>Privacy mode<select bind:value={privacy}><option value="METADATA_ONLY">Metadata only — default</option><option value="REDACTED">Redacted prompt text</option><option value="FULL">Full prompt collection</option></select></label><p class="muted">Metadata mode discards prompts, diffs and arbitrary metadata. Redacted mode removes common credential patterns from prompt text; it cannot guarantee removal of every secret.</p><label class="checkbox"><input type="checkbox" bind:checked={trackDiffs}/>Allow diffs in full collection mode</label><p class="caption">Changes apply to new events. Previously stored events retain their original collection policy.</p><button class="primary" disabled={busy}>Save settings</button></form></section>{/if}
 {/if}<footer>rubberai · Evidence over assumptions.</footer></main></div>
{/if}
